# Generated by Django 2.1.1 on 2018-09-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
